CREATE TABLE OnlineOrders (
    OrderID INT PRIMARY KEY IDENTITY(1,1),
    FirstName NVARCHAR(100) NOT NULL,
    LastName NVARCHAR(100) NOT NULL,
    Address NVARCHAR(255) NOT NULL,
    Apartment NVARCHAR(100) NOT NULL,
    City NVARCHAR(100) NOT NULL,
    Province NVARCHAR(100) NOT NULL,
    ZipCode NVARCHAR(20) NOT NULL,
    ContactNumber NVARCHAR(20) NOT NULL,
    TotalAmount DECIMAL(18,2) NOT NULL,
    OrderStatus NVARCHAR(20) NOT NULL,
    OrderDate DATETIME DEFAULT GETDATE() NOT NULL
);
