CREATE TABLE [dbo].[Orders]
(
    OrderID INT IDENTITY(1,1) PRIMARY KEY,
    OrderDate DATETIME NOT NULL DEFAULT GETDATE(),
    TotalAmount DECIMAL(10,2) NOT NULL,
    IsFulfilled BIT NOT NULL DEFAULT 0
);
